---
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install dependencias
      ansible.builtin.apt:
        pkg: 
          - python3
          - python3-pymysql
          - mysql-server
        state: latest

    - name: Create a new database with name 'wordpress_db'
      community.mysql.mysql_db:
        name: '{{ wp_db_name }}'
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock

    - name: Create database user with name 'u_wordpress' and password '12345' with all database privileges
      community.mysql.mysql_user:
        name: '{{ wp_db_user }}'
        password: '{{ wp_db_user }}'
        column_case_sensitive: false
        priv: '{{ wp_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER'
        state: present
        login_unix_socket: /run/mysqld/mysqld.sock
        host: '{{ item }}'
      with_items: #lista de IPs permitidos para conexão do usuário ao mysql
      - 'localhost'
      - '127.0.0.1'
      - '{{ wp_ip }}'

    - name: Configure database
      ansible.builtin.replace:
         path: /etc/mysql/mysql.conf.d/mysqld.cnf
         regexp: '127.0.0.1'
         replace: '0.0.0.0'
      notify:
        - restart mysql