---
    - name: 'Atualiza o SO'
      shell: sudo apt update -y && sudo apt upgrade -y
      become: yes

    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt: 
        name: ['php', 'apache2', 'libapache2-mod-php', 'php-gd', 'php-mbstring', 'php-xml' ,'python3', 'php-mysql']  
        state: latest
      become: yes