---
- hosts: all
  tasks: 
    - name: 'Atualiza o SO'
      shell: sudo apt update -y && sudo apt upgrade -y
      become: yes

    - name: 'Instala o pip'
      shell: sudo apt install pip -y
      become: yes

    - name: 'Instala o pymsql'
      shell: sudo pip install pymysql
      become: yes

    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt: 
        name: ['php', 'apache2', 'mysql-server', 'libapache2-mod-php', 'php-mysql', 'php-gd', 'php-mbstring', 'php-xml', 'python3']  
        state: latest
      become: yes

  #  - name: Muda a senha do usuário root no MySQL
   #   mysql_user:
    #    name: root
     #   host: localhost
      #  password: root
       # login_unix_socket: /var/run/mysqld/mysqld.sock
      #become: true

    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt: 
        name: ['php', 'apache2', 'mysql-server', 'libapache2-mod-php', 'php-mysql', 'php-gd', 'php-mbstring', 'php-xml', 'python3']  
        state: latest
      become: yes
        
    - name: 'Cria o banco MySQL'
      mysql_db:
        name: wordpress_db
        login_user: root
        login_password: root
        state: present

    - name: Cria usuário do MySQL
      community.mysql.mysql_user:
        login_user: root
        login_password: root
        name: wordpress_user
        password: 12345
        priv: 'wordpress_db.*:ALL'
        state: present
      become: yes
    
 #   - name: Baixa o arquivo de instalação do Wordpress
  #    ansible.builtin.get_url:
   #     url: 'https://wordpress.org/latest.tar.gz'
    #    dest: '/tmp/wordpress.tar.gz'

 #   - name: Descompacta o wordpress
  #    ansible.builtin.unarchive:
   #     src: '/tmp/wordpress.tar.gz'
    #    dest: /var/www/
     #   remote_src: yes
     # become: yes
            
    - name: editando nome do arquivo
      copy:
        src: /var/www/wordpress/wp-config-sample.php
        dest: /var/www/wordpress/wp-config.php
        remote_src: yes
      become: yes
          
    - name: Configura o wp-config com as entradas do banco de dados
      replace:
        path: /var/www/wordpress/wp-config.php
        regexp: '{{ item.regex }}'
        replace: '{{ item.value }}'
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db'}
        - { regex: 'username_here', value: 'wordpress_use'}
        - { regex: 'password_here', value: 'root'}
      become: yes