---
# CONFIGURANDO DATABASE
- hosts: database
  vars_files:
      - vars/database.yml
      - vars/vars.yml

  roles: 
    - mysql
    
# CONFIGURANDO WORDPRESS
- hosts: wordpress
  vars_files:
    - vars/wordpress.yml
    - vars/vars.yml

  roles: 
    - webserver
    - wordpress


    
