---
- hosts: database
  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes

  tasks: 
    - name: 'Atualiza o SO'
      shell: sudo apt update -y && sudo apt upgrade -y
      become: yes

    - name: 'Instala o pip'
      shell: sudo apt install pip -y
      become: yes

    - name: 'Instala o pymsql'
      shell: sudo pip install pymysql
      become: yes

    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt: 
        name: ['php','php-gd','mysql-server', 'php-mysql','php-mbstring', 'php-xml']  
        state: latest
      become: yes

    - name: Muda a senha do usuário root no MySQL
      mysql_user:
        name: root
        host: localhost
        password: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
      become: true

    - name: 'Cria o banco MySQL'
      mysql_db:
        name: wordpress_db
        login_user: root
        login_password: root
        state: present

    - name: Cria usuário do MySQL
      community.mysql.mysql_user:
        login_user: root
        login_password: root
        name: wordpress_user
        password: 12345
        priv: 'wordpress_db.*:ALL'
        state: present
        host: "{{ item }}"
      with_items:
      - 'localhost'
      - '127.0.0.1'
      - '192.168.56.250'
    - name: Configura mysql para aceitar conexões remotas
      copy:
        src: 'files/my.cnf'
        dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
      become: yes
      notify:
        - restart mysql

- hosts: wordpress
  handlers:
    - name: restart apache
      service: 
        name: apache2 
        state: restarted
      become: yes

  tasks: 
    - name: 'Atualiza o SO'
      shell: sudo apt update -y && sudo apt upgrade -y
      become: yes

    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt: 
        name: ['php', 'apache2', 'libapache2-mod-php', 'php-gd', 'php-mbstring', 'php-xml' ,'python3', 'php-mysql']  
        state: latest
      become: yes
    
    - name: Baixa o arquivo de instalação do Wordpress
      ansible.builtin.get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'

    - name: Descompacta o wordpress
      ansible.builtin.unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: /var/www/
        remote_src: yes
      become: yes
            
    - name: editando nome do arquivo
      copy:
        src: /var/www/wordpress/wp-config-sample.php
        dest: /var/www/wordpress/wp-config.php
        remote_src: yes
      become: yes
          
    - name: Configura o wp-config com as entradas do banco de dados
      replace:
        path: /var/www/wordpress/wp-config.php
        regexp: '{{ item.regex }}'
        replace: '{{ item.value }}'
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db'}
        - { regex: 'username_here', value: 'wordpress_user'}
        - { regex: 'password_here', value: '12345'}
        - { regex: 'localhost', value: '192.168.56.249'}
      become: yes

    - name: Configurando o apache para servir ao wordpress
      copy:
        src: 'files/000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify:
        - restart apache